### ISSUE TITLE
Mac: tegn problemer.

### ISSUE THREAD

**Issue by Dyrhoi** [datsoftlyngby/MessageClient#4]
Hej Christian, som du allerede ved skriver den sjove tegn (firkanter) på Mac, i hvert fald for vores gruppe..

De samme problemer kommer ikke i terminalen men kun i messageclienten.
<img width="1170" alt="chadchatproblemmac" src="https://user-images.githubusercontent.com/39205283/94784440-6f46f680-03ce-11eb-8216-29047a6c9d0e.png">

Det er også underligt at terminalen kan printe _emojis_ ud men clienten ikke kan. Da den godt kan på Windows.
Er det måske et Font valg som Mac ikke supportere korrekt?

**Comment by kalhauge** [comment]
@Dyrhoi kan du måske sende mig IP'en som den ligger på? :)
