### ISSUE TITLE
Null ved socket.close

### ISSUE THREAD

**Issue by ariktwena** [datsoftlyngby/MessageClient#5]
Når vi vil exit vores chat benytter vi os af socket.close for at slutte forbindelsen til vores server. Men når vi kører det gennem din klient, så får vi et evigt loop af "null" når vi vil exit. Hvis vi fjerne din socket.close, så virker det :) 
![Skærmbillede 2020-10-03 kl  05 29 10](https://user-images.githubusercontent.com/35962411/94982282-822a0a00-0539-11eb-8bca-5b9aeb15d097.jpg)
![Skærmbillede 2020-10-03 kl  05 29 20](https://user-images.githubusercontent.com/35962411/94982283-835b3700-0539-11eb-9899-426d0c50790d.jpg)

**Comment by kalhauge** [comment]
Fixed!
